employers = ["9g Enterprises dba SurveyVitals",
"Acist Medical Systems",
"ACR Homes",
"Actual Software Inc.",
"AcuStaf",
"Aerotek",
"All Flex Flexible Circuits, LLC,",
"Allina Health",
"Amazon",
"American Engineering Testing Inc",
"Ameriprise Financial, Inc.",
"Antea Group USA",
"Apex Systems",
"Architecture Technology Corporation",
"Arkema Inc.",
"BAE Systems",
"Baxter Healthcare",
"BD (Becton, Dickinson & Company)",
"Be The Match/NMDP",
"Benchmark Electronics",
"Best Buy",
"Blue Sages Inc.",
"Blueprint Solutions",
"Boston Scientific",
"Brady Corporation",
"Braun Intertec Corporation",
"Brooksource",
"Buhler Incorporated",
"Cambria USA",
"Capella University",
"Cargill",
"Caterpillar, Inc.",
"CenterPoint Energy",
"CenturyLink",
"Certusoft, Inc.",
"City of Minneapolis, MN",
"Code42",
"Cognizant Technology Solutions",
"CommScope",
"Corval Group",
"COUNTRY Financial",
"Cray, Inc.",
"Daikin Applied",
"Daugherty Business Solutions",
"Dell, Inc.",
"Detector Electronics Corporation",
"Digi International",
"Ecolab",
"Edge Consulting Engineers",
"Egan Company",
"Emerson",
"Epic",
"Esri",
"Experis Manpower Group",
"Express Scripts",
"Fairview Health Services",
"Fast Enterprises, LLC",
"Federal Reserve Bank of Minneapolis",
"Fishbowl Solutions, Inc.",
"Ford Motor Company",
"Foth",
"Fredrikson & Byron, P.A.",
"Gausman & Moore Associates, Inc.",
"General Dynamics Mission Systems",
"General Mills",
"George Konik Associates, Inc.",
"Gerdau",
"GNP Company",
"Graco Incorporated",
"Greenheck / Innovent",
"Hawkins, Inc.",
"Hennepin County, MN",
"HighJump Software",
"Hormel Foods Corporation",
"Horwitz NS/I",
"HR Green Company",
"HUSCO International",
"Hutchinson Technology Inc.",
"IBM",
"Ingersoll Rand",
"Intellectual Property Institute Mitchell Hamline School of Law",
"Jamf",
"Karges-Faulconbridge, Inc.",
"Kimley-Horn & Associates",
"KLJ",
"Knight Engineers & Architects",
"Lab Support",
"Land O’Lakes",
"LANDESK Software, Inc.",
"LasX Industries, Inc.",
"Leidos",
"LHB, Inc.",
"Logic PD",
"Marvin Windows and Doors",
"MatrixCare",
"Maverick Software Consulting",
"MAXIMUS",
"Mayo Clinic",
"Mead & Hunt, Inc.",
"MediaBeacon, Inc.",
"Meditech",
"Medtronic, Inc.",
"Metropolitan Council",
"MGA Research Corporation",
"Micron Technology, Inc.",
"Minco",
"Minnesota Reading Corps and Minnesota Math Corps",
"Minnesota Technical Assistance Program (MnTAP)",
"MN Dept. of Transportation",
"National Instruments",
"National Research Mentoring Network",
"New Hudson Facades",
"Nilfisk, Inc.",
"Nol-Tec Systems, Inc.",
"Nonin Medical, Inc.",
"Northern Technologies, LLC",
"NV5, Global",
"Omnitracs",
"Open Access Technology International (OATI), Inc.",
"Open Systems International, Inc.",
"Pace Analytical Services, Inc.",
"PaR Systems, Inc.",
"Pearson VUE",
"PERBIX",
"Perficient, Inc.",
"POWER Engineers, Inc.",
"Pratt & Whitney",
"R+L Carriers",
"Rani Engineering, Inc.",
"Red Flint Group, LLC",
"RFA Engineering",
"Rockwell Automation",
"Schenk Vision",
"Schlumberger",
"SciTechsperience Internship Program; a program of the Minnesota High Tech Association",
"Securian Financial Group",
"Sensata Technologies, Inc.",
"SICK, Inc.",
"Siemens Industry Inc., Digital Grid Business Unit",
"Smart Data Solutions",
"Sogeti USA LLC",
"SPS Commerce",
"St. Jude Medical",
"Starkey Hearing Technologies",
"StatRad",
"SUPERVALU",
"Target Corporation",
"Target Stores & Distribution",
"Tennant Company",
"The Schwan Food Company",
"The Travelers Companies, Inc.",
"Thomson Reuters",
"TKDA",
"TSI Incorporated",
"Twin City Fan Companies, Ltd.",
"U.S. Bank",
"U.S. Department of State, Bureau of Diplomatic Security",
"U.S. Fish & Wildlife Service",
"U.S. Naval Research Laboratory",
"U.S. Water Services",
"United States Marine Corps Officer Programs",
"UnitedHealth Group",
"University of Minnesota – Energy Management",
"Upsher-Smith Laboratories, Inc.",
"U.S. Navy",
"UTC Aerospace Systems",
"VAA",
"Veritas Technologies, LLC.",
"Verso Corporation",
"VERUM Staffing, LLC",
"Virtual Radiologic",
"Vital, A Toshiba Medical Systems Group Company",
"Wagner Spray Tech Corporation",
"Wells Fargo – Technology",
"West Monroe Partners",
"Willis Towers Watson",
"WSP| Parsons Brinckerhoff",
"Xcel Energy"]
